apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-ns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.13.0
      helm:
        valueFiles:
          - $values-repo/nginx-ingress/values.yaml
    - repoURL: https://github.com/padminisys/ingress-nginx-ns.git
      targetRevision: HEAD
      ref: values-repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: satish-kaushik-t45d6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true