apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-lb-pool
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/graitcloud/apps.git
    targetRevision: HEAD
    path: nginx-ingress/lb-cilium
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    syncWaves:
      - wave: -1  # Deploy before nginx-ingress