controller:
  kind: Deployment
  hostNetwork: false
  dnsPolicy: ClusterFirst

  # Keep SSL passthrough if you need backends to terminate TLS themselves
  extraArgs:
    enable-ssl-passthrough: ""

  # Enable LoadBalancer service for Cilium IP pool
  service:
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      lbipam.cilium.io/ips: "188.68.62.169"

  # >>> NEW: nginx config for real client IPs safely (no proxy in front) <<<
  config:
    use-proxy-protocol: "false"
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    real-ip-header: "X-Forwarded-For"
    proxy-real-ip-cidr: "127.0.0.1/32"
  # ^ Trust only localhost as a header source; all internet XFF is ignored.
  #   NGINX will still set X-Forwarded-For to the real socket IP so your apps see the true client IP.

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
