fullnameOverride: "satish"
controller:
  scope:
    enabled: true
  kind: Deployment
  replicaCount: 1
  hostNetwork: false
  dnsPolicy: ClusterFirst
  watchIngressWithoutClass: false

  nodeSelector:
    kubernetes.io/hostname: psys-centos-1

  labels:
    padmini.systems/network-permission: allow
    padmini.systems/tenant-resource-type: ingress
  
  ingressClass: nginx-satish
  
  ingressClassResource:
    name: nginx-satish
    enabled: true
    default: false

  admissionWebhooks:
    enabled: false

  publishService:
    enabled: true

  config:
    use-proxy-protocol: "false"
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    real-ip-header: "X-Forwarded-For"
    proxy-real-ip-cidr: "127.0.0.1/32"

  extraArgs:
    enable-ssl-passthrough: ""

  service:
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      lbipam.cilium.io/ips: "188.68.62.169"
    labels:
      ip-source: nginx-ingress-lb-pool

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
      
rbac:
  create: true
  scope: true